config/routes.rb
Rails.application.routes.draw do





  get 'flags/toggleflag'
  get 'pages/togglemod'



  get 'users/:id/videos' => 'users#videos'
  get 'users/:id/playlists' => 'users#playlists'
  get 'users/:id/comments' => 'users#comments'
  get 'users/:id/stats' => 'users#stats'
  get 'users/:id/bulbs' => 'users#bulbs'
  get 'users/:id/bulbs/given' => 'users#bulbsgiven'
  get 'users/:id/bulbs/received' => 'users#bulbstaken'

  get 'notifications/markread'
  get 'notifications/markallread'
  get 'notifications/tomod'
  get 'notifications/frommod'
  resources :notifications

get 'inbox' => 'notifications#index'

  get 'videos/search'
  get 'contact' => 'pages#contact'
  get 'privacy' => 'pages#privacy'
  get 'playlists/createplaylist'
  get 'newplaylist' => 'playlists#createplaylist'
  get 'addtoplaylist' => 'playlists#addtoplaylist'
  get 'sources' => 'pages#sources'

  get 'permissions/togglensfw'
  get 'nsfw' => 'videos#nsfw'
  get 'categories' => 'pages#twocats'
  get 'category' => 'pages#category'

  get 'top/viewed'
  get 'top/loved'
  get 'top/hated'
  get 'top/controversial'
  get 'top/playlists/loved' => 'top#lovedplaylists'
  get 'top/playlists/viewed' => 'top#viewedplaylists'
  get 'top/week/loved' => 'top#lovedweek'
  get 'top/week/hated' =>'top#hatedweek'
  get 'top/month/loved' => 'top#lovedmonth'
  get 'top/month/hated' => 'top#hatedmonth'
  get 'top/week/viewed' => 'top#viewedweek'
  get 'top/month/viewed' => 'top#viewedmonth'
  get 'top/week/controversial' => 'top#controweek'
  get 'top/month/controversial' => 'top#contromonth'
  get 'top/hot'

  get 'rules' => 'pages#rules'
  get 'mod' => 'pages#mod'
    get 'admin' => 'pages#admin'
  get 'bans/mod'
  get 'bans/index'

  get 'users/show'
  get 'videos/tags'

    resources :comments do
      resources :comments
      resources :bulbs
          resources :flags
    end

    resources :playlists do
      resources :comments
      resources :bulbs
          resources :flags
      resources :items do
        resources :videos
      end
    end

  get 'videos/check'
  get 'videos/index'
  get 'videos/new'
  get 'videos/edit'
  get 'videos/show'

    resources :videos do
      resources :comments
      resources :bulbs
          resources :flags
    end

  get 'recent' => 'pages#recent'
  get 'rank/asc' => 'pages#asc'
  get 'rank/desc' => 'pages#desc'
  resources :statuses
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users do
    resources :statuses
    resources :permissions
  resources :notifications
  resources :bulbs
end
end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:user_id, :brief, :rating, :long)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<div class="card bg-secondary">
<%= bootstrap_form_with(model: status, local: true) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= form.hidden_field :user_id, value: current_user.id, required: true %>

  <div class="field">
    <%= form.label :brief, 'A brief description of your situation (max 120 characters)' %>
    <%= form.text_field :brief, maxlength: 120 %>
  </div>

  <div class="field">
    <%= form.label :rating, 'Rate your level of safety/security [physical, emotional, financial, medical] from 1(good) to 10(bad), enter 0 to not disclose. This will change the color of your row.' %>
    <%= form.number_field :rating, min: 0, max: 10 %>
  </div>

  <div class="field">
    <%= form.label :long, 'Write as much as you want here' %>
    <%= form.cktext_area :long %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h2>My Status</h2>

<div class="card bg-secondary
<% if current_user.status %>
      <% if current_user.status.rating %>
     bgcolor<%= current_user.status.rating %>
    <% end %>
    <% end %>">
  <div class="card-header" id="heading<%= current_user.id %>">
        <h5 class="card-title">
        <%= current_user.name %>

      </h5>

    <span class="text-black"><% if current_user.status %>
    <% if current_user.status.brief %>
  <%= current_user.status.brief %>
  <% end %>
  <% end %></span>
  </div>


    <div class="card-body">
      <p class="card-text">
        <% if current_user.status %>
        <% if current_user.status.long %>
      <%= simple_format(current_user.status.long, {}, sanitize: false)%>
      <% end %>
      <% end %>
    </p>
    </div>
  </div>


<% if current_user.status %>
        <%= link_to 'Edit', edit_user_status_path(current_user, current_user.status) %>
    <% end %>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<h2>My Status</h2>

<div class="card bg-secondary
<% if current_user.status %>
      <% if current_user.status.rating %>
     bgcolor<%= current_user.status.rating %>
    <% end %>
    <% end %>">
  <div class="card-header" id="heading<%= current_user.id %>">
        <h5 class="card-title">
        <%= current_user.name %>

      </h5>
    <span class="text-black"><% if current_user.status %>
    <% if current_user.status.brief %>
  <%= current_user.status.brief %>
  <% end %>
  <% end %></span>
  </div>

  <div id="collapse<%= current_user.id %>" class="" aria-labelledby="heading<%= current_user.id %>" data-parent="#allcurrent_users">
    <div class="card-body">
      <p class="card-text">
        <% if current_user.status %>
        <% if current_user.status.long %>
      <%= simple_format(current_user.status.long, {}, sanitize: false)%>
      <% end %>
      <% end %>
    </p>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>