config/routes.rb
Rails.application.routes.draw do





  get 'flags/toggleflag'
  get 'pages/togglemod'



  get 'users/:id/videos' => 'users#videos'
  get 'users/:id/playlists' => 'users#playlists'
  get 'users/:id/comments' => 'users#comments'
  get 'users/:id/stats' => 'users#stats'
  get 'users/:id/bulbs' => 'users#bulbs'
  get 'users/:id/bulbs/given' => 'users#bulbsgiven'
  get 'users/:id/bulbs/received' => 'users#bulbstaken'

  get 'notifications/markread'
  get 'notifications/markallread'
  get 'notifications/tomod'
  get 'notifications/frommod'
  resources :notifications

get 'inbox' => 'notifications#index'

  get 'videos/search'
  get 'contact' => 'pages#contact'
  get 'privacy' => 'pages#privacy'
  get 'playlists/createplaylist'
  get 'newplaylist' => 'playlists#createplaylist'
  get 'addtoplaylist' => 'playlists#addtoplaylist'
  get 'sources' => 'pages#sources'

  get 'permissions/togglensfw'
  get 'nsfw' => 'videos#nsfw'
  get 'categories' => 'pages#twocats'
  get 'category' => 'pages#category'

  get 'top/viewed'
  get 'top/loved'
  get 'top/hated'
  get 'top/controversial'
  get 'top/playlists/loved' => 'top#lovedplaylists'
  get 'top/playlists/viewed' => 'top#viewedplaylists'
  get 'top/week/loved' => 'top#lovedweek'
  get 'top/week/hated' =>'top#hatedweek'
  get 'top/month/loved' => 'top#lovedmonth'
  get 'top/month/hated' => 'top#hatedmonth'
  get 'top/week/viewed' => 'top#viewedweek'
  get 'top/month/viewed' => 'top#viewedmonth'
  get 'top/week/controversial' => 'top#controweek'
  get 'top/month/controversial' => 'top#contromonth'
  get 'top/hot'

  get 'rules' => 'pages#rules'
  get 'mod' => 'pages#mod'
    get 'admin' => 'pages#admin'
  get 'bans/mod'
  get 'bans/index'

  get 'users/show'
  get 'videos/tags'

    resources :comments do
      resources :comments
      resources :bulbs
          resources :flags
    end

    resources :playlists do
      resources :comments
      resources :bulbs
          resources :flags
      resources :items do
        resources :videos
      end
    end

  get 'videos/check'
  get 'videos/index'
  get 'videos/new'
  get 'videos/edit'
  get 'videos/show'

    resources :videos do
      resources :comments
      resources :bulbs
          resources :flags
    end

  get 'recent' => 'pages#recent'
  get 'rank/asc' => 'pages#asc'
  get 'rank/desc' => 'pages#desc'
  resources :statuses
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users do
    resources :statuses
    resources :permissions
  resources :notifications
  resources :bulbs
end
end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :status, dependent: :destroy
  has_many :videos, dependent: :destroy
    has_many :playlists, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bulbs, dependent: :destroy
    has_many :flags, dependent: :destroy
  has_one :permission, dependent: :destroy
      has_many :notifications, dependent: :destroy
after_create :make_permission

private

def make_permission
  @permission = Permission.create(
    user_id: self.id,
    is_horny: false,
    can_post_video: true,
    can_bulb: true,
    can_comment: true
  )
  @permission.save!
end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #     @user = User.new(sign_up_params)
  #     respond_to do |format|
  #       if verify_recaptcha(model: @user) && params[:age_confirm] == true && params[:terms] == true && @user.save
  #         format.html { redirect_to @user, notice: 'Video was successfully created.' }
  #         format.json { render :show, status: :created, location: @user }
  #       else
  #         format.html { render :new }
  #         format.json { render json: @user.errors, status: :unprocessable_entity }
  #       end
  #     end
  # end

  def create
    if verify_recaptcha
      super
    else
      build_resource(sign_up_params)
      clean_up_passwords(resource)
      flash.now[:alert] = "There was an error with the recaptcha code below. Please re-enter the code."
      flash.delete :recaptcha_error
      render :new
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy, :stats, :bulbs, :videos, :playlsits, :bulbsgiven, :bulbstaken]
  def show
    @user = User.find(params[:id])
    @comments = @user.comments.order("created_at DESC").first(10)
    @array = []
    @videos = @user.videos.each do |item|
      @array << item.bulbs
    end

    @comments = @user.comments.each do |item|
      @array << item.bulbs
    end

    @playlists = @user.playlists.each do |item|
      @array << item.bulbs
    end
    @array.flatten!
if !@array.nil?
@bulbs_to_user = Bulb.where(id: @array.map(&:id))
else
  @bulbs_to_user = 0
end
      if current_user.permission.is_horny?
    @videos = @user.videos.order("created_at DESC").first(10)
    @playlists = @user.playlists.order("created_at DESC").first(10)
  else
    @videos = @user.videos.where.not('category1 = ?', 'NSFW').where.not('category2 = ?', 'NSFW').order("created_at DESC").first(10)
    @playlists = @user.playlists.where.not('category1 = ?', 'NSFW').where.not('category2 = ?', 'NSFW').order("created_at DESC").first(10)
  end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

    def stats
    end

def videos
  if current_user.permission.is_horny?
      @videos = @user.videos.order("created_at DESC").first(10).paginate(:page => params[:page], :per_page => 24)
    else
        @videos = @user.videos.where.not('category1 = ?', 'NSFW').where.not('category2 = ?', 'NSFW').order("created_at DESC").paginate(:page => params[:page], :per_page => 24)
    end
end

def playlists

end

    def bulbs

      @bulbs = @user.bulbs
      @redbulbs = @bulbs.where(color: "red")
      @greenbulbs = @bulbs.where(color: "green")
      all_color_values = Bulb.order(:color).pluck(:color).uniq
      @given_bulbs = all_color_values.map do |color|
        { name: color, data: @bulbs.where(color: color).group_by_day(:created_at).count }
      end
      @given_bulbs_pie = @bulbs.group(:color).count

      @array = []
      @videos = @user.videos.each do |item|
        @array << item.bulbs
      end

      @comments = @user.comments.each do |item|
        @array << item.bulbs
      end

      @playlists = @user.playlists.each do |item|
        @array << item.bulbs
      end

      @array.flatten!
if !@array.nil?
@bulbs_to_user = Bulb.where(id: @array.map(&:id))
@display_to_user = true
      @bulbs_to_user_pie = @bulbs_to_user.group(:color).count
else
@bulbs_to_user = Bulb.all
@display_to_user = false
end
      @recieved_bulbs = all_color_values.map do |color|
        { name: color, data: @bulbs_to_user.where(color: color).group_by_day(:created_at).count }
      end


    end

def bulbsgiven
  @bulbs = @user.bulbs
  Bulb.all.each do |bulb|
    if bulb.bulbable_type = "Video" && Video.find_by_id(bulb.bulbable_id).nil?
      bulb.destroy!
    end
  end
  @redbulbs = @bulbs.where(color: "red")
  @greenbulbs = @bulbs.where(color: "green")
end

def bulbstaken
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/bulbs.html.erb
<div class="box rules">
  <% if !@user.bulbs.first.nil? %>
<h2>Bulbs Given by <%= @user.name %></h2>
<%= pie_chart(@given_bulbs_pie, donut: true, colors: [ '#00ff0a', '#ff0000' ], height: "150px", width: "300px", legend: "right", library: { pieSliceText: 'value' }) %>
<%= line_chart(@given_bulbs,
colors: [ '#00ff0a', '#ff0000' ]) %>
<%= link_to "List of all bulbs given ", user_path(@user) + "/bulbs/given" %>
<% end %>

<% if @display_to_user == true %>

<%= pie_chart(@bulbs_to_user_pie, donut: true, colors: [ '#00ff0a', '#ff0000' ], height: "150px", width: "300px", legend: "right", library: { pieSliceText: 'value' }) %>
<h2>Bulbs Given to <%= @user.name %></h2>
<%= line_chart(@recieved_bulbs,
colors: [ '#00ff0a', '#ff0000' ]) %>
<% @bulbs.each do |bulb| %>

<% end %>
<%# bulb.id %> <%# bulb.color %> <%# bulb.bulbable_type %> <%# bulb.bulbable_id %>
<!-- <br> -->
List of all bulbs received
<% end %>

</div>

app/views/users/bulbsgiven.html.erb
<div class="box rules">
<h2>Bulbs given by <%= @user.name %></h2>
<%= column_chart [
  { name: "green", data: @greenbulbs.group(:bulbable_type).count },
  { name: "red", data: @redbulbs.group(:bulbable_type).count }
],
    colors: [ '#00ff0a', '#ff0000' ],
    height: '200px' %>
<div class="bulbslist">
  <% @bulbs.each do |bulb| %>
    <div><%= image_tag(bulb.color + "bulb.png") %></div>
  <% if bulb.bulbable_type = "Video" %>
  <% @source = Video.find_by_id(bulb.bulbable_id) %>
  <% elsif bulb.bulbable_type = "Playlist" %>
    <% @source = Playlist.find_by_id(bulb.bulbable_id) %>
  <% else %>
        <% @source = Comment.find_by_id(bulb.bulbable_id) %>
         <% until @layer.parent_type == "Video" || @layer.parent_type == "Playlist" %>
           <% @layer.parent = @layer.parent.parent %>
         <% end %>
  <% end %>
  <div><%= @source.user.name %></div>
  <% if bulb.bulbable_type != "Comment" %>
    <div><%= @source.title %></div>
    <% else %>
    <div>Comment</div>
    <% end %>



    <div><%= bulb.created_at.strftime("%D, %l:%M%P") %></div>
  <%end%>
</div>


</div>

app/views/users/bulbstaken.html.erb
<h1>Users#bulbstaken</h1>
<p>Find me in app/views/users/bulbstaken.html.erb</p>

app/views/users/comments.html.erb
<h1>Users#comments</h1>
<p>Find me in app/views/users/comments.html.erb</p>

app/views/users/playlists.html.erb
<h1>Users#playlists</h1>
<p>Find me in app/views/users/playlists.html.erb</p>

app/views/users/show.html.erb
<div class="box rules">
<h2><%= @user.name %></h2>

<% if @user.permission.can_comment == false || @user.permission.can_post_video == false || @user.permission.can_bulb == false %>
<div class="banbox">
<p>
<%= @user.name %> is banned from:<br>
<% if @user.permission.can_post_video == false %>
Submitting videos until <%= @user.permission.video_ban_end.strftime("%B %e, %Y") %><br>
<% end %>
<% if @user.permission.can_comment == false %>
Commenting until <%= @user.permission.comment_ban_end.strftime("%B %e, %Y") %><br>
<% end %>
<% if @user.permission.can_bulb == false %>
Bulbing until <%= @user.permission.bulb_ban_end.strftime("%B %e, %Y") %><br>
<% end %>
Ban reason: <%= @user.permission.reason_for_ban %>
</p>
</div>
<% end %>
<h3><small><%= link_to "Bulb stats", user_bulbs_path(@user) %></small></h3>
<div class="bulbtable">
Total bulbs:
<div class="bulboutergrid">
  <div>Given
    <div class="bulbinnergrid">
          <div>
            <%= image_tag("greenbulb.png") %> <%= @user.bulbs.where(color: "green").count %>
          </div>
          <div>
            <%= image_tag("redbulb.png") %> <%= @user.bulbs.where(color: "red").count %>
          </div>
    </div>
  </div>
    <% if @bulbs_to_user == 0 %>
  <div>Recieved
    <div class="bulbinnergrid">
          <div>
          <%= image_tag("greenbulb.png") %> 0
          </div>
          <div>
          <%= image_tag("redbulb.png") %> 0
          </div>
    </div>
  </div>
    <% else %>
      <div>Received
    <div class="bulbinnergrid">
          <div>
            <%= image_tag("greenbulb.png") %> <%= @bulbs_to_user.where(color: "green").count %>
          </div>
          <div>
          <%= image_tag("redbulb.png") %> <%= @bulbs_to_user.where(color: "red").count %>
          </div>
    </div>
</div>
<% end %>
</div>
</div>
<h3><small>Videos submitted by <%= @user.name %> </small></h2>
  <ul>
<% @videos.each do |video| %>
<li>  <%= link_to video.title, video_path(video) %></li>
<% end %>
</ul>
<%= link_to "More...", user_path(@user) + "/videos" %>

  <h3>Playlists by <%= @user.name %> </h2>
  <% @user.playlists.each do |playlist| %>
    <%= link_to playlist.title, playlist_path(playlist) %><br>
<% end %>
<%= link_to "More...", user_path(@user) + "/playlists" %>

<% if current_user.permission.is_mod == true || current_user.permission.is_admin == true %>
<div class="useradminpanel">
Admin options:<br>
Change user's name:
<%= form_with(model: [@user], local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <% @user.errors.full_messages.each do |message| %>
      <% end %>
    </div>
  <% end %>

    <%= form.text_field :name %>
    <%= form.submit %>
<% end %>


Ban or suspend user:
  <div class="modgrid">
<%= render 'permissions/form', user: @user %>
</div>

10 most recent comments:
<div class="recentcomments">
  <% @user.comments.order("created_at DESC").limit(10).each do |comment| %>
   <% @layer = comment %>
    <% until @layer.parent_type == "Video" %>
      <% @layer.parent = @layer.parent.parent %>
    <% end %>
       <%= link_to @layer.parent.title, video_path(@layer.parent) %>
       <%= form_with(model: [comment], local: true) do |form| %>
         <% if comment.errors.any? %>
           <div id="error_explanation">
             <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
             <% comment.errors.full_messages.each do |message| %>
             <% end %>
           </div>
         <% end %>

           <%= form.text_area :body %>
           <%= form.submit %>
       <% end %>
<%= button_to 'Delete', comment, method: :delete, data: { confirm: "Are you sure you want to delete this comment? All replies to this comment INCLUDING THOSE BY OTHER USERS will also be deleted. PLEASE CHECK THE VIDEO PAGE FIRST.\n\n" + comment.user.name + ": "+ comment.body + "" } %><hr>
  <% end %><hr>
</div>
</div>
<% end %>
</div>

app/views/users/stats.html.erb
<h1>Users#stats</h1>
<p>Find me in app/views/users/stats.html.erb</p>

app/views/users/videos.html.erb
<div class="box">
  <h2>Videos submited by <%= link_to @user.name, user_path(@user) %></h2>
  <%= render 'videos/allvideos' %>
</div>