config/routes.rb
Rails.application.routes.draw do





  get 'flags/toggleflag'
  get 'pages/togglemod'



  get 'users/:id/videos' => 'users#videos'
  get 'users/:id/playlists' => 'users#playlists'
  get 'users/:id/comments' => 'users#comments'
  get 'users/:id/stats' => 'users#stats'
  get 'users/:id/bulbs' => 'users#bulbs'
  get 'users/:id/bulbs/given' => 'users#bulbsgiven'
  get 'users/:id/bulbs/received' => 'users#bulbstaken'

  get 'notifications/markread'
  get 'notifications/markallread'
  get 'notifications/tomod'
  get 'notifications/frommod'
  resources :notifications

get 'inbox' => 'notifications#index'

  get 'videos/search'
  get 'contact' => 'pages#contact'
  get 'privacy' => 'pages#privacy'
  get 'playlists/createplaylist'
  get 'newplaylist' => 'playlists#createplaylist'
  get 'addtoplaylist' => 'playlists#addtoplaylist'
  get 'sources' => 'pages#sources'

  get 'permissions/togglensfw'
  get 'nsfw' => 'videos#nsfw'
  get 'categories' => 'pages#twocats'
  get 'category' => 'pages#category'

  get 'top/viewed'
  get 'top/loved'
  get 'top/hated'
  get 'top/controversial'
  get 'top/playlists/loved' => 'top#lovedplaylists'
  get 'top/playlists/viewed' => 'top#viewedplaylists'
  get 'top/week/loved' => 'top#lovedweek'
  get 'top/week/hated' =>'top#hatedweek'
  get 'top/month/loved' => 'top#lovedmonth'
  get 'top/month/hated' => 'top#hatedmonth'
  get 'top/week/viewed' => 'top#viewedweek'
  get 'top/month/viewed' => 'top#viewedmonth'
  get 'top/week/controversial' => 'top#controweek'
  get 'top/month/controversial' => 'top#contromonth'
  get 'top/hot'

  get 'rules' => 'pages#rules'
  get 'mod' => 'pages#mod'
    get 'admin' => 'pages#admin'
  get 'bans/mod'
  get 'bans/index'

  get 'users/show'
  get 'videos/tags'

    resources :comments do
      resources :comments
      resources :bulbs
          resources :flags
    end

    resources :playlists do
      resources :comments
      resources :bulbs
          resources :flags
      resources :items do
        resources :videos
      end
    end

  get 'videos/check'
  get 'videos/index'
  get 'videos/new'
  get 'videos/edit'
  get 'videos/show'

    resources :videos do
      resources :comments
      resources :bulbs
          resources :flags
    end

  get 'recent' => 'pages#recent'
  get 'rank/asc' => 'pages#asc'
  get 'rank/desc' => 'pages#desc'
  resources :statuses
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users do
    resources :statuses
    resources :permissions
  resources :notifications
  resources :bulbs
end
end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :parent, dependent: :destroy
  has_many :bulbs, as: :bulbable, dependent: :destroy
  has_many :flags, as: :flaggable, dependent: :destroy
  validates :user_id, presence: true
  validates :id_code, presence: true
  validates :provider, presence: true
  validates :title, presence: true, length: {maximum: 255}
  validates :category1, presence: true
  validates :embed_url, presence: true
  validates :embed_code, presence: true
  before_save :default_values

def default_values
  self.user_id ||= current_user.id
end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  content_security_policy false, only: :show
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.where.not('category1 = ?', 'NSFW').where.not('category2 = ?', 'NSFW').paginate(:page => params[:page], :per_page => 24)
  @bulb = Bulb.new
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
        @comment = Comment.new
        @bulb = Bulb.new
        @tags = @video.tags.split(",")
        @video.increment!(:plays)
        @video.updated_at = DateTime.now
        @video.save!
        @fullscreen = true
        @items = Item.where(video_id: @video.id)
        @playlist_ids = []
        @items.each do |item|
          @playlist_ids << item.playlist
        end
        @playlist_ids.uniq!
        @playlists = Playlist.where(id: @playlist_ids.map(&:id))
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  def search

@terms = params[:terms].downcase
@username = params[:username]

@search_videos = params[:search_videos]
@search_comments = params[:search_comments]
@search_playlists = params[:search_playlists]
@use_name = params[:use_name]

@use_title = params[:use_title]
@use_tags = params[:use_tags]
@use_description = params[:use_description]
if @use_name == nil
  @username = nil
end
@matches = []


if @use_name == "on" && @search_videos == "on"

  if @terms == nil || @terms == ""
    Video.all.each do |video|
      if video.user.name.downcase.include?(@username)
        @matches << video
      end
    end

  else

      if @use_title == "on"
        Video.all.each do |video|
          if video.title.downcase.include?(@terms) && video.user.name.downcase.include?(@username)
            @matches << video
          end
        end
      end

      if @use_tags == "on"
        Video.all.each do |video|
          if video.tags.downcase.include?(@terms) && video.user.name.downcase.include?(@username)
            @matches << video
          end
        end
      end

      if @use_description == "on"
        Video.all.each do |video|
          if video.description.downcase.include?(@terms) && video.user.name.downcase.include?(@username)
            @matches << video
          end
        end
      end

  end

elsif @use_name == "on" && @search_playlists == "on"

  if @terms == nil || @terms == ""
    Playlist.all.each do |playlist|
      if playlist.user.name.downcase.include?(@username)
        @matches << playlist
      end
    end

  else

      if @use_title == "on"
        Playlist.all.each do |playlist|
          if playlist.title.downcase.include?(@terms) && playlist.user.name.downcase.include?(@username)
            @matches << playlist
          end
        end
      end

      if @use_tags == "on"
        Playlist.all.each do |playlist|
          if playlist.tags.downcase.include?(@terms) && playlist.user.name.downcase.include?(@username)
            @matches << playlist
          end
        end
      end

      if @use_description == "on"
        Playlist.all.each do |playlist|
          if playlist.description.downcase.include?(@terms) && playlist.user.name.downcase.include?(@username)
            @matches << playlist
          end
        end
      end

  end

elsif @use_name == "on" && @search_comments == "on"

  if @terms == nil || @terms == ""
    Comment.all.each do |comment|
      if comment.user.name.downcase.include?(@username)
        @matches << comment
      end
    end

  else


        Comment.all.each do |comment|
          if comment.body.downcase.include?(@terms) && comment.user.name.downcase.include?(@username)
            @matches << comment
          end
        end


  end


end



if @search_playlists == "on" && @use_name == nil
  if @use_title == "on"
    Playlist.all.each do |playlist|
      if playlist.title.downcase.include?(@terms)
        @matches << playlist
      end
    end
  end

  if @use_tags == "on"
    Playlist.all.each do |playlist|
      if playlist.tags.downcase.include?(@terms)
        @matches << playlist
      end
    end
  end

  if @use_description == "on"
    Playlist.all.each do |playlist|
      if playlist.description.downcase.include?(@terms)
        @matches << playlist
      end
    end
  end
end




if @search_videos == "on" && @use_name == nil
  if @use_title == "on"
    Video.all.each do |video|
      if video.title.downcase.include?(@terms)
        @matches << video
      end
    end
  end

  if @use_tags == "on"
    Video.all.each do |video|
      if video.tags.downcase.include?(@terms)
        @matches << video
      end
    end
  end

  if @use_description == "on"
    Video.all.each do |video|
      if video.description.downcase.include?(@terms)
        @matches << video
      end
    end
  end
end


if @use_name == nil && @search_comments == "on"
        Comment.all.each do |comment|
          if comment.body.downcase.include?(@terms)
            @matches << comment
          end
      end
  end

@matches = @matches.uniq

 if @search_videos == "on"
@videos = Video.where(id: @matches.map(&:id)).order("created_at ASC").paginate(:page => params[:page], :per_page => 24)
elsif @search_playlists == "on"
  @playlists = Playlist.where(id: @matches.map(&:id)).order("created_at ASC").paginate(:page => params[:page], :per_page => 24)
elsif @search_comments == "on"
  @comments = Comment.where(id: @matches.map(&:id)).order("created_at ASC").paginate(:page => params[:page], :per_page => 20)
else
  @videos = nil
end

  @bulb = Bulb.new
  end

  def check

    @videos = Video.all
    @video = Video.new
    @url = params[:url]

    if (@url.include?("youtube.com") || @url.include?("vimeo.com") || @url.include?("wistia.com") || @url.include?("dailymotion.com") || @url.include?("youtu.be"))
    @query = VideoInfo.new(@url)
      @video_id = @query.video_id
      @title = @query.title
      @thumbnail = @query.thumbnail_medium
      @provider = @query.provider
      @embed_url = @query.embed_url
      @embed_code = @query.embed_code
      @duration = @query.duration
      @description = @video.description
      @dupes = @videos.where("provider = ? and id_code = ?", @provider, @video_id)
  elsif (@url.include?("twitter.com") || @url.include?("://t.co"))
    response = HTTParty.get('https://publish.twitter.com/oembed?url=' + @url)
    @query = @url
    @video_id = @query
    @embed_url = @query
    @duration = 0
    @title = ""
    @description = ActionController::Base.helpers.sanitize(response["html"], tags:[])
    @embed_code = response["html"]
    @provider = "Twitter"
    @thumbnail = ActionController::Base.helpers.image_path("twitter.png")
    @dupes = @videos.where("provider = ? and id_code = ?", @provider, @video_id)
  elsif (@url.include?("instagram.com") || @url.include?("://instagr.am"))
    response = HTTParty.get('https://api.instagram.com/oembed?url=' + @url)
    @query = @url
    @video_id = response['media_id']
    @embed_url = @query
    @duration = 0
    @title =  response["title"]
    @description = ActionController::Base.helpers.sanitize(response["html"], tags:[])
    @embed_code = response["html"]
    @provider = "Instagram"
    @thumbnail = response['thumbnail_url']
    @dupes = @videos.where("provider = ? and id_code = ?", @provider, @video_id)
  elsif @url.include?("tiktok.com")
    response = HTTParty.get('https://www.tiktok.com/oembed?url=' + @url)
    @query = @url
    @video_id = @query
    @embed_url = @query
    @duration = 0
    @title =  response["title"]
    @description = response["title"]
    @embed_code = response["html"]
    @provider = "TikTok"
    @thumbnail = response['thumbnail_url']
    @dupes = @videos.where("provider = ? and id_code = ?", @provider, @video_id)
  elsif (@url.include?("facebook.com") || @url.include?("://fb.com"))
    @query = @url
    if @query.include?("videos/")
      @parts = @query.split("videos/")
    elsif @query.include?("watch/?v=")
      @parts = @query.split("watch/?v=")
    end
    if @parts[1].include?("/")
    @video_id = @parts[1].chomp!("/")
  else
    @video_id = @parts[1]
  end
    @embed_url = "https://www.facebook.com/facebook/videos/" + @video_id + "/"
    @duration = 0
    @title =  @query
    @description = @query
    @embed_code = "<div id='fb-root'></div>
<script async defer crossorigin='anonymous' src='https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v6.0&appId=403358119713189&autoLogAppEvents=1'></script>
<div class='fb-video' data-href='#{@embed_url}' data-width='auto' data-show-text='false'></div>"
    @provider = "Facebook"
    @thumbnail = ActionController::Base.helpers.image_path("facebook.png")
    @dupes = @videos.where("provider = ? and id_code = ?", @provider, @video_id)
  elsif @url.include?("giphy.com/gifs")
    @query = @url
    @parts = @query.split("gifs/")
    @video_id = @parts[1]
    @embed_url = @query
    @duration = 0
    @title =  ""
    @description = ""
    @embed_code = "<div style='width:100%;height:0;padding-bottom:100%;position:relative;'><iframe src='https://giphy.com/embed/#{@video_id}' width='100%' height='100%' style='position:absolute' frameBorder='0' class='giphy-embed' allowFullScreen></iframe></div><p><a href='https://giphy.com/gifs/#{@video_id}'>via GIPHY</a></p>"
    @provider = "Giphy"
    @thumbnail = "https://media.giphy.com/media/#{@video_id}/giphy.gif"
    @dupes = @videos.where("provider = ? and id_code = ?", @provider, @video_id)
  elsif @url.include?("gfycat.com")
    @query = @url
    @parts = @query.split("gfycat.com/")
    @idparts = @parts[1].split("-", 2)
    @video_id = @idparts[0]
    if @idparts.length > 1
      @video_stub = "-" + @idparts[1]
    else
      @video_stub = ""
    end
    @embed_url = @query
    @duration = 0
    @title =  ""
    @description = ""

app/helpers/videos_helper.rb
module VideosHelper
  def link_hashtags(comment)
    comment.gsub(/(http|https|ftp|ftps)\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(\/\S*)?/) { |match| link_to match, match }
  end

  def redbulbers(source)
    arr = []
    source.bulbs.where(color: "red").each do |bulb|
       arr << bulb.user
    end
    return User.where(id: arr.map(&:id))
  end

  def greenbulbers(source)
    arr = []
    source.bulbs.where(color: "green").each do |bulb|
       arr << bulb.user
    end
    return User.where(id: arr.map(&:id))
  end

end

app/views/videos/_allvideos.html.erb
<div id="allvideos">

<% @videos.each do |video| %>
<% @pagetype = "videos" %>
<div id="vid<%= video.id %>" class="vidgrid">



  <div class="thumbnailContainer">


  <% @gb = video.bulbs.where(color: "green").count %>
  <% @rb = video.bulbs.where(color: "red").count %>

      <%if (@gb >= 5 && @rb < 5) || (@rb >= 5 && @gb >= 5 && (@gb / @rb >= 2)) %>

            <div class="thumbgreen" style="background-image: url(<%= video.thumbnail.html_safe %>);">

      <% elsif (@rb >= 5 && @gb < 5) || (@gb >= 5 && @rb >= 5 && (@rb / @gb >= 2)) %>

            <div class="thumbred" style="background-image: url(<%= video.thumbnail.html_safe %>);">

      <% elsif @rb >= 5 && @gb >= 5 %>

            <div class="thumbyellow" style="background-image: url(<%= video.thumbnail.html_safe %>);">

      <% else %>
    <div class="thumb" style="background-image: url(<%= video.thumbnail.html_safe %>);">
      <% end %>





      <div class="thumbbulbs bulbs inline">
<button class="notbutton"> <i class="fas fa-eye"></i> <%= video.plays %> </button>
       <% if Bulb.where("user_id = ? and bulbable_type = ? and bulbable_id = ?", current_user.id, "Video", video.id).exists? || current_user.permission.can_bulb == false || video.user == current_user  %>

        <%= render 'bulbs/disabled', bulbable: video, color: "green" %>
        <%= render 'bulbs/disabled', bulbable: video, color: "red" %>
        <% else %>
  <%= render 'bulbs/form', bulbable: video, bulb: @bulb, color: "green" %>
  <%= render 'bulbs/form', bulbable: video, bulb: @bulb, color: "red" %>
  <% end %>

  </div>

<span class="vidsubtitle"><h4><%= link_to(video) do %>
  <%= video.title.truncate_words(20).truncate(120) %></h4>
  <% end %>
     <span class="category vidsubcat"><%= link_to video.category1, category_path(:query => video.category1) %></span>
     <% if !video.category2.blank? %>
     <span class="category vidsubcat"><%= link_to video.category2, category_path(:query => video.category2) %></span>
     <% end %>
    <span class="vidsubname">
    <%= link_to user_path(video.user) do %>
    <i class="fas fa-user"></i>
    <%= video.user.name %>
    <%end%>
    </span>

   </span>
    </div>


  </div>

  <div class="descriptionContainer">
<div class="descinner">
    <p>


      <%= video.description.truncate_words(50).truncate(250) %></p>

  </div>
    </div>

</div>

<% end %>

</div>

app/views/videos/_checkform.html.erb
<div class="checkform" id="checkform"><h4>Submit a video</h4>
<%= form_tag('/videos/check/', method: 'get' ) do %>
<small><%= link_to "List of Supported Sources", sources_path %></small><br>
    <%= url_field_tag :url, params[:url], required: true, placeholder: "Enter the URL" %>
    <%= button_tag :submit do %>
    Submit
<% end %>

<% end %>
</div>

app/views/videos/_form.html.erb
<div class="submitform">
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.hidden_field :id_code, value: @video_id, :required => true %>
    <%= form.hidden_field :provider, value: @provider, :required => true %>
    <%= form.hidden_field :thumbnail, value: @thumbnail, :required => true %>
    <%= form.hidden_field :embed_url, value: @embed_url, :required => true %>
    <%= form.hidden_field :embed_code, value: @embed_code, :required => true %>
    <%= form.hidden_field :duration, value: @duration, :required => true %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, value: @title, :required => true, :maxlength => 255 %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, value: @description, :required => true %>
  </div>

  <div class="field">
    <%= form.label :tags, "Separate tags with commas" %>
    <%= form.text_field :tags %>
  </div>

  <div class="field">
    <%= form.label :category1, "Categories" %>
    <%= form.select :category1, options_for_select(@categories), {:include_blank => 'Select A Category'}, {:required => true, :class => 'select'} %>
    <%= form.select :category2, options_for_select(@categories), {:include_blank => 'Select A Category'} %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/videos/_show.html.erb
<% @video = video %>
<div class="vidplayergrid">
  <div id="iframecontainer">
    <div id="linkModalContainer" class="invisible">
      <div class="linkModal">
        Embedding may not be supported for this video.<br>
        View this video at its original source:<br> <a href="<%= video.embed_url %>" target="_blank"><%= video.embed_url %></a><br>
        If the video loads under this message, please disregard.<br>
        <button onclick="dismissLink()">Dismiss this message</button>
      </div>
    </div>
<% if ((video.category1 == "NSFW" || video.category2 == "NSFW") && !current_user.permission.is_horny? ) %>
    <div id="nsfwModalContainer" class="">
      <div class="nsfwModal">
        This video is hidden because you are in safe mode.<br>
        If you would like to see it, you can either turn safe mode off, or just dismiss this message to view it anyway while leaving your settings intact.<br>
                      <%= render 'permissions/nsfwform', user: current_user %>
        <button onclick="dismissNsfw()">Just show me the video</button>
      </div>
    </div>
    <% end %>
    <div id="playlistModalContainer" class="invisible">
      <div class="playlistModal">
        <% if current_user.playlists.first != nil %>
                <button>Add to Existing Playlist</button>
        <div id="addTOExistingPlaylist">        <p>Add to Existing Playlist</p></div>
<%= render 'playlists/addtoexisting' %>
        <% end %>

        <button>Create New Playlist</button>
<%= render 'playlists/newplaylist' %>
        <button onclick="closePlaylistModal()">Close</button>
      </div>
    </div>

      <%= video.embed_code.html_safe %>
  </div>
  <div>

    <%= render 'layouts/topbar' %>
<% if @is_playlist == true %>
<%= render 'playlists/playlistinfo' %>
<% end %>

    <div class="title full">
    <h4>
      <%= video.title %>
    </h4>
  </div>

      <p>Posted by   <span class="vidsubname"><%= link_to video.user.name, user_path(video.user) %></span> on <%= video.created_at.strftime("%B %e, %Y") %></p>





<p>
  <span class="category"><%= link_to video.category1, category_path(:query => video.category1) %></span>
  <% if !video.category2.blank? %>
  <span class="category"><%= link_to video.category2, category_path(:query => video.category2) %></span>
  <% end %>
  </p>


<% if !@tags.nil? %>
    <p>

      <% @tags.each do |tag| %>
      <span class="tag"> <%= link_to tag, videos_tags_path(query: tag) %> </span>
      <% end %>
    </p>
    <% end %>


  <div class="bulbs inline">
<button class="notbutton"> <i class="fas fa-eye"></i> <%= video.plays %> </button>
      <% if Bulb.where("user_id = ? and bulbable_type = ? and bulbable_id = ?", current_user.id, "Video", video.id).exists? || current_user.permission.can_bulb == false || video.user == current_user %>

      <%= render 'bulbs/disabled', bulbable: video, color: "green" %>
      <%= render 'bulbs/disabled', bulbable: video, color: "red" %>
      <% else %>
<%= render 'bulbs/form', bulbable: video, bulb: @bulb, color: "green" %>
<%= render 'bulbs/form', bulbable: video, bulb: @bulb, color: "red" %>
<% end %>
<button class="bulbs inline" onclick="showBulbers('video',<%= video.id %>)">?</button>
<%= render 'playlists/addbutton' %>
<%= render 'flags/form', flaggable: video, flag: @flag %>
<% if current_user.permission.is_mod == true || current_user.permission.is_admin == true %>
<div class="modActions"> Mod Actions:
<%= button_to 'Delete', video, method: :delete, data: { confirm: "Are you sure you want to delete this video? All comments on this video will also be deleted.\n\n" + video.title + "" } %>
</div>
<% end %>

</div>


<div class="bulbers collapsed" id="videobulbers<%= video.id %>">
  <div>
  <%= image_tag("greenbulb.png") %>
  <% greenbulbers(video).each do |bulber| %>
  <span class="vidsubname"><%= link_to bulber.name, user_path(bulber) %></span>
  <% end %>
</div>
<div>
  <%= image_tag("redbulb.png") %>
  <% redbulbers(video).each do |bulber| %>
  <span class="vidsubname"><%= link_to bulber.name, user_path(bulber) %></span>
  <% end %>
</div>
</div>

<div class="videodescription">
  <p>
  <%= video.description %>
</p>
<% if @playlists.first != nil %>

<div class="listVideoPlaylists">
<h6>Playlists Featuring This Video</h6>
<ul>
  <% @playlists.each do |playlist| %>
<li>  <%= link_to playlist.title, playlist_path(playlist) %> by <%= link_to playlist.user.name, user_path(playlist.user) %></li>
  <% end %>
</ul>
</div>

<% end %>
</div>
  </div>

</div>
<div class="comments">
  <% if (video.user == current_user && video.comments.count == 0) %>
  You can't leave the first comment on your own video.
  <% else %>
  <%= render 'comments/form', comment: @comment %>
<% end %>

<%= render partial: 'comments/comment', collection: video.comments %>

</div>

app/views/videos/check.html.erb
  <div class="box">
    <% if current_user.permission.can_post_video == true %>

<% if @dupes.first != nil %>
  <% @dupes.each do |video| %>

  <h2>Duplicate video found</h2>
  <center>
    <p>
    <img class="centered-image" src="<%= video.thumbnail %>">
  </p>
    <p>
    <%= link_to video.title, video_path(video) %> posted on <%= video.created_at.strftime("%B %e, %Y") %> by <%= link_to video.user.name, user_path(video.user) %></center>
</p>
  <% end %>
<% else %>
no dupes found
<div><img class="centered-image" src="<%= @thumbnail %>"></div>
<div><%= render 'form', video: @video %></div>

<%  end %>
<%  end %>
  </div>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<% video = VideoInfo.new('https://vimeo.com/76979871') %>
<img src="<%= video.thumbnail_small %>"><br>
<h2><%= video.title %></h2>
<p><%= video.description %></p>
<%= video.embed_code.html_safe %>


<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Id code</th>
      <th>Provider</th>
      <th>Title</th>
      <th>Duration</th>
      <th>Description</th>
      <th>Thumbnail</th>
      <th>Embed url</th>
      <th>Embed code</th>
      <th>Tags</th>
      <th>Category1</th>
      <th>Category2</th>
      <th>Upbulbs</th>
      <th>Downbulbs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.user_id %></td>
        <td><%= video.id_code %></td>
        <td><%= video.provider %></td>
        <td><%= video.title %></td>
        <td><%= video.duration %></td>
        <td><%= video.description %></td>
        <td><%= video.thumbnail %></td>
        <td><%= video.embed_url %></td>
        <td><%= video.embed_code %></td>
        <td><%= video.tags %></td>
        <td><%= video.category1 %></td>
        <td><%= video.category2 %></td>
        <td><%= video.upbulbs %></td>
        <td><%= video.downbulbs %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/nsfw.html.erb
<div class="box">
    <% if current_user.permission.is_horny? %>
  <h2>NSFW</h2>
  <%= render 'videos/allvideos' %>
  <% else %>
  Access denied
  <% end %>
</div>

app/views/videos/search.html.erb
<% if @videos != nil && @playlists == nil %>

    <%= render 'videos/allvideos' %>
    <% elsif @videos == nil && @playlists != nil %>
<div class="box rules">
<h3>PLAYLISTS</h3>
<ul>
    <% @playlists.each do |playlist| %>
    <li><%= link_to playlist.title, playlist_path(playlist) %></li>
    <% end %>
  </ul>
<%= render 'layouts/pagination', videos: @playlists %>
</div>

<% elsif @videos == nil && @playlists == nil && @comments != nil %>
<div class="box rules">
<h3>COMMENTS</h3>
<ul>
<% @comments.each do |comment| %>
 <% @layer = comment %>
  <% until @layer.parent_type == "Video" || @layer.parent_type == "Playlist"  %>
    <% @layer.parent = @layer.parent.parent %>
  <% end %>
<% split = comment.body.split(@terms, 2) %>
<% split1 = split[0].reverse.truncate_words(15).truncate(75).reverse %>
<% split2 = split[1].truncate_words(15).truncate(75) %>
<li><%= split1 %><span class="highlightsearchterm"><%= @terms %></span><%= split2 %><br> by <%= link_to comment.user.name, user_path(comment.user) %> on
  <% if @layer.parent_type == "Video" %>
   <%= link_to @layer.parent.title, video_path(@layer.parent, anchor: "comment" + comment.id.to_s ) %>
   <% else %>
      <%= link_to @layer.parent.title, playlist_path(@layer.parent, anchor: "comment" + comment.id.to_s ) %>
   <% end %>
 </li>
<% end %>
</ul>
<%= render 'layouts/pagination', videos: @comments %>
</div>
    <% else %>
    <div class="box rules">
    No matches
  </div>
    <%end %>

app/views/videos/show.html.erb
  <%= render 'videos/show', video: @video %>

app/views/videos/tags.html.erb
<div class="box">
    <h2><%= @tag %></h2>
  <%= render 'videos/allvideos' %>
</div>