config/routes.rb
Rails.application.routes.draw do





  get 'flags/toggleflag'
  get 'pages/togglemod'



  get 'users/:id/videos' => 'users#videos'
  get 'users/:id/playlists' => 'users#playlists'
  get 'users/:id/comments' => 'users#comments'
  get 'users/:id/stats' => 'users#stats'
  get 'users/:id/bulbs' => 'users#bulbs'
  get 'users/:id/bulbs/given' => 'users#bulbsgiven'
  get 'users/:id/bulbs/received' => 'users#bulbstaken'

  get 'notifications/markread'
  get 'notifications/markallread'
  get 'notifications/tomod'
  get 'notifications/frommod'
  resources :notifications

get 'inbox' => 'notifications#index'

  get 'videos/search'
  get 'contact' => 'pages#contact'
  get 'privacy' => 'pages#privacy'
  get 'playlists/createplaylist'
  get 'newplaylist' => 'playlists#createplaylist'
  get 'addtoplaylist' => 'playlists#addtoplaylist'
  get 'sources' => 'pages#sources'

  get 'permissions/togglensfw'
  get 'nsfw' => 'videos#nsfw'
  get 'categories' => 'pages#twocats'
  get 'category' => 'pages#category'

  get 'top/viewed'
  get 'top/loved'
  get 'top/hated'
  get 'top/controversial'
  get 'top/playlists/loved' => 'top#lovedplaylists'
  get 'top/playlists/viewed' => 'top#viewedplaylists'
  get 'top/week/loved' => 'top#lovedweek'
  get 'top/week/hated' =>'top#hatedweek'
  get 'top/month/loved' => 'top#lovedmonth'
  get 'top/month/hated' => 'top#hatedmonth'
  get 'top/week/viewed' => 'top#viewedweek'
  get 'top/month/viewed' => 'top#viewedmonth'
  get 'top/week/controversial' => 'top#controweek'
  get 'top/month/controversial' => 'top#contromonth'
  get 'top/hot'

  get 'rules' => 'pages#rules'
  get 'mod' => 'pages#mod'
    get 'admin' => 'pages#admin'
  get 'bans/mod'
  get 'bans/index'

  get 'users/show'
  get 'videos/tags'

    resources :comments do
      resources :comments
      resources :bulbs
          resources :flags
    end

    resources :playlists do
      resources :comments
      resources :bulbs
          resources :flags
      resources :items do
        resources :videos
      end
    end

  get 'videos/check'
  get 'videos/index'
  get 'videos/new'
  get 'videos/edit'
  get 'videos/show'

    resources :videos do
      resources :comments
      resources :bulbs
          resources :flags
    end

  get 'recent' => 'pages#recent'
  get 'rank/asc' => 'pages#asc'
  get 'rank/desc' => 'pages#desc'
  resources :statuses
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :users do
    resources :statuses
    resources :permissions
  resources :notifications
  resources :bulbs
end
end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :items
  has_many :comments, as: :parent, dependent: :destroy
  has_many :bulbs, as: :bulbable, dependent: :destroy
  has_many :flags, as: :flaggable, dependent: :destroy
  has_many :items, dependent: :destroy
  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 255}
  validates :category1, presence: true
  before_save :default_values

def default_values
  self.user_id ||= current_user.id
end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
            @fullscreen = true
    @is_playlist = true
    @ids = []
    @videos = @playlist.items.order(:sort).all.paginate(:page => params[:page], :per_page => 1)


    @bulb = Bulb.new
    @comment = Comment.new
            @playlist.increment!(:plays)
            @playlist.updated_at = DateTime.now
            @playlist.save!
@thisvid = Video.find_by_id((@videos.first).video_id)
@thisvid.increment!(:plays)
@thisvid.updated_at = DateTime.now
@thisvid.save!

@items = Item.where(video_id: @thisvid.id)
@playlist_ids = []
@items.each do |item|
  @playlist_ids << item.playlist
end
@playlist_ids.uniq!
@playlists = Playlist.where(id: @playlist_ids.map(&:id))

  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
    @items = @playlist.items.order(:sort).all
  end

  def createplaylist
    @video = Video.find_by_id(params[:video_id])
    @playlist = Playlist.new(
      user_id: current_user.id,
      title: params[:title],
      description: params[:description],
      category1: params[:category1],
      category2: params[:category2],
      tags: params[:tags],
    )
    @playlist.save!
    if @playlist.save
    Notification.create(
      user_id: @video.user.id,
      body: "Your video '#{view_context.link_to @video.title, video_path(@video)}' was added to #{view_context.link_to @playlist.user.name, user_path(@playlist.user)}'s playlist '#{view_context.link_to @playlist.title, playlist_path(@playlist)}'."
    )
  end
    @first_item = Item.new(
      playlist_id: @playlist.id,
      video_id: @video.id
    )
    @first_item.save!
    redirect_to playlist_path(@playlist)
end

def addtoplaylist
    @video = Video.find_by_id(params[:video_id])
    @playlist = Playlist.find_by_id(params[:playlist])
    @count = @playlist.items.count
    @new_item = Item.new(
      playlist_id: @playlist.id,
      video_id: @video.id,
      sort: @count + 1
    )
    @new_item.save!
    if @new_item.save
    Notification.create(
      user_id: @video.user.id,
      body: "Your video '#{view_context.link_to @video.title, video_path(@video)}' was added to #{view_context.link_to @playlist.user.name, user_path(@playlist.user)}'s playlist '#{view_context.link_to @playlist.title, playlist_path(@playlist)}'."
    )
  end
    redirect_to playlist_path(@playlist)
end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playlist_params
      params.require(:playlist).permit(:user_id, :title, :description, :category1, :category2, :tags, :plays)
    end
end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_addbutton.html.erb
<button class='add_to_playlist' onclick='openPlaylistModal()'><i class='fas fa-plus'></i> <i class='fas fa-list'></i></button>

app/views/playlists/_addtoexisting.html.erb
<div class="playlistform addTOExistingPlaylist">
  <%= form_tag('/addtoplaylist/', method: 'get' ) do |form| %>
  <%= hidden_field_tag :video_id, params[:video_id], value: params[:id] %>
      <%= select_tag :playlist, options_for_select(current_user.playlists.collect { |list| [list.title, list.id]}) %>
      <%= submit_tag "Add" %>
  <% end %>
</div>

app/views/playlists/_editoritem.html.erb
<tr id="<%= item.sortable_id %>">
  <td>
    <div class="sortbox">

      <div class="thumb minithumb" style="background-image: url(<%= video.thumbnail.html_safe %>);">
      </div>

      <div class="caption inline">
        <h4 class="sorttitle">
        <%= link_to(video) do %>
        <%= video.title.truncate_words(20).truncate(120) %>
        </h4>
        <% end %>

        <div class="desccolumns">
          <div>
            <p>
              <%= video.description.truncate_words(20).truncate(120) %>
            </p>
          </div>

          <div class="right">

            <span class="vidsubname">
              <%= link_to user_path(video.user) do %>
              <i class="fas fa-user"></i>
              <%= video.user.name %>
              <%end%>
            </span>

            <%= button_to 'Remove', [@playlist, item], method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>

    </div>
  </td>
</tr>

app/views/playlists/_form.html.erb
<%= simple_form_for(playlist, local: true) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.label :category1, "Categories" %>
    <%= f.select :category1, options_for_select(@categories, f.object.category1 || playlist.category1), {:include_blank => 'Select A Category'}, {:required => true, :class => 'select'} %>
    <%= f.select :category2, options_for_select(@categories, f.object.category2 || playlist.category2), {:include_blank => 'Select A Category'} %><br>
    <%= f.input :tags %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/playlists/_newplaylist.html.erb
<div class="playlistform createplaylist">
  <%= form_tag('/newplaylist/', method: 'get' ) do |form| %>
  <%= hidden_field_tag :video_id, params[:video_id], value: params[:id] %>
  <%= text_field_tag :title, nil, :required => true, :placeholder => "Playlist Title", :maxlength => 255 %>
  <%= text_area_tag :description, nil, :required => true, :placeholder => "Describe your playlist-- you can edit this later." %>
  <%= select_tag :category1, options_for_select(@categories), {:include_blank => 'Select A Category'} %>
  <%= select_tag :category2, options_for_select(@categories), {:include_blank => 'Select A Category'} %>
  <%= text_field_tag :tags, nil, :placeholder => "Tags separated by commas" %>
      <%= submit_tag "Create" %>
  <% end %>
</div>

app/views/playlists/_playlistinfo.html.erb
<div class="title full">
<h4>
  <%= @playlist.title %>
</h4>
</div>
<div><p>A playlist by    <span class="vidsubname"><%= link_to @playlist.user.name, user_path(@playlist.user) %></span></p>

<p>  <%= @playlist.description %>
  <p>
    <span class="category"><%= link_to @playlist.category1, category_path(:query => @playlist.category1) %></span>
    <% if !@playlist.category2.blank? %>
    <span class="category"><%= link_to @playlist.category2, category_path(:query => @playlist.category2) %></span>
    <% end %>
    </p>

    <% if !@tags.nil? %>
        <p>

          <% @tags.each do |tag| %>
          <span class="tag"> <%= link_to tag, videos_tags_path(query: tag) %> </span>
          <% end %>
        </p>
        <% end %>

     <div class="bulbs inline">
<button class="notbutton"> <i class="fas fa-eye"></i> <%= @playlist.plays %> </button>
      <% if Bulb.where("user_id = ? and bulbable_type = ? and bulbable_id = ?", current_user.id, "Playlist", @playlist.id).exists? || current_user.permission.can_bulb == false || @playlist.user == current_user %>

      <%= render 'bulbs/disabled', bulbable: @playlist, color: "green" %>
      <%= render 'bulbs/disabled', bulbable: @playlist, color: "red" %>
      <% else %>
<%= render 'bulbs/form', bulbable: @playlist, bulb: @bulb, color: "green" %>
<%= render 'bulbs/form', bulbable: @playlist, bulb: @bulb, color: "red" %>
<% end %>
<button class="bulbs inline" onclick="showBulbers('playlist',<%= @playlist.id %>)">?</button>


    </div>
    <p>
      <strong>Videos:</strong>
      <ol>
        <% x = 1 %>
      <% @playlist.items.each do |item| %>

       <% @video = Video.find_by_id(item.video_id) %>
       <li> <%= link_to @video.title, playlist_path(@playlist, :page => x ) %></li>
       <% x += 1 %>
      <% end %>
    </ol>
    </p>
<%= render 'layouts/paginationmini' %>
  <% if @playlist.user == current_user || current_user.permission.is_mod == true || current_user.permission.is_admin == true %>
    <%= link_to 'Edit', edit_playlist_path(@playlist) %> |
    <%= link_to 'All Playlists', playlists_path %>
    <% end %>
</div>

app/views/playlists/addtoplaylist.html.erb
<h1>Playlists#addtoplaylist</h1>
<p>Find me in app/views/playlists/addtoplaylist.html.erb</p>

app/views/playlists/createplaylist.html.erb
<h1>Playlists#crateplaylist</h1>
<p>Find me in app/views/playlists/crateplaylist.html.erb</p>

app/views/playlists/edit.html.erb
<div class="box rules">

  <% if @playlist.user == current_user || current_user.permission.is_mod == true || current_user.permission.is_admin == true %>
  <h2>Editing Playlist "<%= link_to @playlist.title, playlist_path(@playlist) %>"</h2>
<h3>Basic Info</h3>
<%= render 'form', playlist: @playlist %>
<% else %>
You can not edit another user's playlist.
<% end %>

  <% if @playlist.user == current_user %>
<h3>Videos</h3>
<h4>Drag and Drop to Change Order</h4>
<table>
  <tbody class="sortable">
<% @items.each do |item| %>
<%   video = Video.find_by_id(item.video_id) %>
<%= render 'editoritem', item: item, video: video %>

<% end %>
</tbody>
</table>
<% else %>
You can not edit another user's playlist.
<% end %>

  <% if @playlist.user == current_user || current_user.permission.is_mod == true || current_user.permission.is_admin == true %>
<h3>Delete Playlist</h3>
<%= button_to 'Delete Playlist', @playlist, method: :delete, data: { confirm: 'Are you sure you want to delete this playlist?' } %>
<% else %>
You can not edit another user's playlist.
<% end %>

</div>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>
<div class="box rules">
<h1>Playlists</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Category</th>
      <th>Category</th>
      <th>Tags</th>
      <th>Plays</th>
            <th>Videos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= link_to playlist.user.name, user_path(playlist.user) %></td>
        <td><%= link_to playlist.title, playlist_path(playlist) %></td>
        <td><%= playlist.category1 %></td>
        <td><%= playlist.category2 %></td>
        <td><%= playlist.tags %></td>
        <td><%= playlist.plays %></td>
                <td><%= playlist.items.count %></td>



      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<% @videos.each do |item| %>
  <%= render 'videos/show', video: Video.find_by_id(item.video_id) %>
  <% end %>